### ISSUE TITLE
<-  or get-arrow  in demo.rye fails

### ISSUE THREAD

**Issue by HFolkertH** [refaktor/rye-front#37]
I am testing demo.rye with the latest rye-fyne.exe  on my Windows laptop but it gives an error on the next line:

chk .set-checked 0 <- i <- Data/tasks

![image](https://github.com/user-attachments/assets/4b28ceb4-4ab2-403b-809e-711364de298e)

**Comment by refaktor** [comment]
You probably mean examples/shopping.rye . Please use the build from latest version and it should work:
https://github.com/refaktor/rye-fyne/releases/tag/26

I installed and tested previous binary release (23) and got the same error as you, but the current one works. The example is not written totally (deleting doesn't work), because we made some changes to spreadsheets so that they can also be used as internal state / data structure. This was done on Rye level, so I will update the example too.

**Comment by refaktor** [comment]
Otherwise if you would get a similar error you could use function `probe` that displays a value it receives and returns it also, so you can use it completely inline. Or you could call `enter-console "debuging ..."` above error and you would enter into console when script comes to that point and you can test the expressions and see the values in live situation.

But this was obviously a bug in release 23, so please just use the new one 26.

**Comment by refaktor** [comment]
If bug persists with release 26 please reopen the issue.
